### ISSUE TITLE
Live Testing

### ISSUE THREAD

**Issue by ArshansGithub** [frc-emotion/Crescendo-2024#14]
# Drivetrain
- [x] Setup constants
- [x] Completed teleoperated testing
- [ ] Completed autonomous testing

# Intake
- [x] Setup constants
- [x] Completed teleoperated testing
- [x] Completed autonomous testing

# Shooter
- [x] Setup constants
- [x] Completed teleoperated testing
- [x] Completed autonomous testing

# Pivot
- [x] Setup constants
- [x] Completed teleoperated testing
- [x] Completed autonomous testing

# Climb
- [x] Setup constants
- [x] Completed teleoperated testing

# Vision
- [x] Setup constants
- [ ] Completed teleoperated testing
- [ ] Completed autonomous testing

# Misc
- [ ] Completed teleoperated testing
- [ ] Completed autonomous testing

**Comment by jasonballinger** [comment]
@ArshansGithub is climb auto testing done? 😛

**Comment by ArshansGithub** [comment]
> @ArshansGithub is climb auto testing done? 😛

Not yet unfortunately 😿

**Comment by ArshansGithub** [comment]
Season is over :(
