### ISSUE TITLE
Vision

### ISSUE THREAD

**Issue by jasonballinger** [frc-emotion/Crescendo-2024#2]
- [ ] Aligning to Speaker via apriltags
- [ ] Aligning to AMP via apriltags
- [ ] Drive to Pose (On the fly trajectory generation) via apriltags
- [ ] Interpolation Table for Shooter Macros
- [x] Both shooter angle, robot yaw, and shooter velocity
- [x] LEDs to display the current robot state

**Comment by ArshansGithub** [comment]
Season is over :(
